export type DepositDataSource = "onchain" | "backend";

export type DepositFlowViewModel = {
  source: DepositDataSource;
  amount: string;
  setAmount: (value: string) => void;
  statusMessage: string;
  errorMessage: string;
  isConnected: boolean;
  isMiniPay: boolean;
  isCeloChain: boolean;
  canTransact: boolean;
  hasValidContracts: boolean;
  usdcAddress: string;
  vaultAddress: string;
  walletBalanceDisplay: string;
  allowanceDisplay: string;
  availableBalanceDisplay: string;
  lockedBalanceDisplay: string;
  isWalletBalanceFetching: boolean;
  isAllowanceFetching: boolean;
  isVaultBalanceFetching: boolean;
  needsApproval: boolean;
  approveTxHash: string;
  approveTxUrl: string;
  depositTxHash: string;
  depositTxUrl: string;
  withdrawTxHash: string;
  withdrawTxUrl: string;
  isApproveBusy: boolean;
  isDepositBusy: boolean;
  isWithdrawBusy: boolean;
  disableApproveButton: boolean;
  disableDepositButton: boolean;
  disableWithdrawButton: boolean;
  onApprove: () => Promise<void>;
  onDeposit: () => Promise<void>;
  onWithdraw: () => Promise<void>;
  configMessage: string;
};
